# Generated by Django 4.2.4 on 2023-08-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
