# Generated by Django 4.2.4 on 2023-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='discriptions',
            field=models.TextField(),
        ),
    ]
